Repository dnd-side-project/dnd-10th-1-frontend, pull requests merged in 2024-02, with the labels that each got.

#4 [Kan-29] Drawer를 추가한다.
  components.json
  package-lock.json
  package.json
  src/app/_component/temp-client/index.tsx
  src/app/globals.css
  src/app/page.tsx
  src/components/button/button.stories.tsx
  src/components/button/button.test.tsx
  src/components/button/index.tsx
  src/components/drawer/drawer.stories.tsx
  src/components/drawer/index.tsx
  src/components/input/index.tsx
  src/components/input/input.stories.tsx
  tailwind.config.js
Labels: 📖 storybook, 🚧test

#5 레이아웃 작업
  package-lock.json
  package.json
  src/app/assets/images/splash-logo.png
  src/app/layout.tsx
  src/app/page.tsx
  src/components/splash.tsx
  tailwind.config.js
Labels: 🎨 design, ⚡feat

#6 [KAN-36] tailwind 세팅 수정
  package.json
  src/app/layout.tsx
  src/app/page.tsx
  tailwind.config.js
Labels: 🎨 design, 🔨 refactor

#7 [Kan-29] bottom-sheet 스타일을 추가한다.
  src/components/drawer/drawer.stories.tsx
  src/components/drawer/index.tsx
Labels: 🎨 design, 📖 storybook

#8 온보딩 관련 작업을 진행합니다.
  .storybook/preview.ts
  package-lock.json
  package.json
  src/app/_onboarding/first/first-screen.stories.tsx
  src/app/_onboarding/first/first-screen.tsx
  src/app/_onboarding/first/first.tsx
  src/app/_onboarding/second/second-screen.stories.tsx
  src/app/_onboarding/second/second-screen.tsx
  src/app/_onboarding/second/second.tsx
  src/app/_onboarding/third/third-screen.stories.tsx
  src/app/_onboarding/third/third-screen.tsx
  src/app/_onboarding/third/third.tsx
  src/app/_profile/profile.tsx
  src/app/_splash/splash.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/stackflow.tsx
  src/assets/images/splash-logo.png
  src/assets/svgs/onboarding-first.svg
  src/assets/svgs/onboarding-second.svg
  src/assets/svgs/onboarding-third.svg
  src/components/splash.tsx
Labels: 🎨 design, ⚡feat, 📖 storybook

#10 feat: #9 font를 추가한다
  .storybook/preview.tsx
  src/app/layout.tsx
  src/styles/fonts/Pretendard-Black.woff2
  src/styles/fonts/Pretendard-Bold.woff2
  src/styles/fonts/Pretendard-ExtraBold.woff2
  src/styles/fonts/Pretendard-ExtraLight.woff2
  src/styles/fonts/Pretendard-Light.woff2
  src/styles/fonts/Pretendard-Medium.woff2
  src/styles/fonts/Pretendard-Regular.woff2
  src/styles/fonts/Pretendard-SemiBold.woff2
  src/styles/fonts/Pretendard-Thin.woff2
  src/styles/fonts/pretendard.ts
Labels: 🎨 design, ⚡feat

#17 fix: #16 스토리북 폰트 적용 안되는 문제 수정
  .storybook/main.ts
Labels: ✅fix

#15 feat: #11 프로필 페이지 작업을 진행합니다.
  src/app/_main/components/main-footer/index.tsx
  src/app/_onboarding/first/first.tsx
  src/app/_onboarding/second/second.tsx
  src/app/_onboarding/third/third.tsx
  src/app/_profile/components/profile-input/profile-input.stories.tsx
  src/app/_profile/components/profile-input/profile-input.tsx
  src/app/_profile/profile-screen.stories.tsx
  src/app/_profile/profile-screen.tsx
  src/app/_profile/profile-themes.ts
  src/app/_profile/profile.tsx
  src/assets/svgs/profiles/edit-profile.svg
  src/assets/svgs/profiles/fallback-profile.svg
  src/assets/svgs/profiles/profile-theme-1.svg
  src/assets/svgs/profiles/profile-theme-2.svg
  src/assets/svgs/profiles/profile-theme-3.svg
  src/assets/svgs/profiles/profile-theme-4.svg
  src/assets/svgs/profiles/profile-theme-5.svg
  src/assets/svgs/profiles/profile-theme-6.svg
  src/assets/svgs/profiles/profile-theme-7.svg
  src/assets/svgs/profiles/profile-theme-8.svg
  src/assets/svgs/profiles/x-circle.svg
  src/components/drawer/index.tsx
Labels: 🎨 design, ⚡feat, 📖 storybook

#19 feat: #13 대기화면 스크린 작업을 완료합니다.
  package-lock.json
  package.json
  src/app/_waiting/components/waiting-bottom/index.tsx
  src/app/_waiting/components/waiting-bottom/one-user.tsx
  src/app/_waiting/components/waiting-bottom/user-list.tsx
  src/app/_waiting/components/waiting-top/index.tsx
  src/app/_waiting/types/game.ts
  src/app/_waiting/waiting-screen.stories.tsx
  src/app/_waiting/waiting-screen.tsx
  src/app/_waiting/waiting.tsx
  src/components/app-bar/index.tsx
  src/types/user.ts
  tailwind.config.js
Labels: 🎨 design, ⚡feat, 📖 storybook

#20 refactor: #12 메인 화면 이미지 추가 작업을 완료합니다.
  src/app/_main/components/main-footer/index.tsx
  src/app/_main/components/main-header/index.tsx
  src/app/_main/main-screen.tsx
  src/assets/images/main-character-logo.png
Labels: 🎨 design, 🔨 refactor

#21 feat: #18 게임 선택 화면 작업을 진행합니다.
  src/app/_select-games/select-games-screen.stories.tsx
  src/app/_select-games/select-games-screen.tsx
  src/app/_select-games/select-games.tsx
  src/app/stackflow.tsx
  src/assets/svgs/select-games/blank-game.png
  src/assets/svgs/select-games/mbti-game.png
Labels: 🎨 design, 📖 storybook

#23 feat: #22 애니메이션을 추가합니다.
  package-lock.json
  package.json
  src/components/framer-motion/loading-bar/loading-bar.stories.tsx
  src/components/framer-motion/loading-bar/loading-bar.tsx
  src/components/framer-motion/mbti-result-header-bar/header-nav-bar.stories.tsx
  src/components/framer-motion/mbti-result-header-bar/header-nav-bar.tsx
  src/components/framer-motion/slot-machine/machine-test.tsx
  src/components/framer-motion/slot-machine/slot-machine.stories.tsx
  src/components/framer-motion/slot-machine/slot-machine.tsx
Labels: 🎨 design, ⚡feat, 📖 storybook

#25 fix: 경로문제 해결
  src/components/framer-motion/loading-bar/loading-bar.stories.tsx
Labels: 🐞bug

#32 feat: #30 게임 로딩 스크린을 추가합니다.
  src/app/_game-loading/components/loading-bar/loading-bar.stories.tsx
  src/app/_game-loading/components/loading-bar/loading-bar.tsx
  src/app/_game-loading/game-loading-screen.tsx
  src/app/_game-loading/game-loading.stories.tsx
  src/app/_game-loading/game-loding.tsx
  src/app/globals.css
Labels: 🎨 design, ⚡feat

#33 refactor: #12 메인 스크린 퍼블리싱을 완료합니다.
  src/app/_main/components/main-button/main-button.stories.tsx
  src/app/_main/components/main-button/main-button.tsx
  src/app/_main/components/main-dragbar/index.tsx
  src/app/_main/components/main-footer/index.tsx
  src/app/_main/components/main-header/index.tsx
  src/app/_main/components/main-onboarding/index.tsx
  src/app/_main/main-screen.tsx
  src/app/globals.css
  src/assets/images/main-character-logo.png
  src/assets/images/main/character.png
  src/assets/images/main/line-art.png
  src/assets/svgs/main/main-circle.svg
  src/assets/svgs/main/main-create.svg
  src/assets/svgs/main/main-linear.svg
  src/assets/svgs/main/main-tooltip.svg
  src/components/chip/index.tsx
  src/components/framer-motion/slot-machine/machine-test.tsx
  src/components/framer-motion/slot-machine/slot-machine.stories.tsx
  src/constants/main.ts
  src/hooks/useSlotMachine.tsx
Labels: 🎨 design, 🔨 refactor, 📖 storybook

#35 feat: #31 스몰 토크 스크린 작업을 진행합니다.
  package-lock.json
  package.json
  src/app/_small-talk/components/game-banner/game-banner.stories.tsx
  src/app/_small-talk/components/game-banner/game-banner.tsx
  src/app/_small-talk/components/game-body/game-body.stories.tsx
  src/app/_small-talk/components/game-body/game-body.tsx
  src/app/_small-talk/components/game-header/game-header.tsx
  src/app/_small-talk/components/game-result-box/game-result-box.tsx
  src/app/_small-talk/game-input/game-input-screen.stories.tsx
  src/app/_small-talk/game-input/game-input-screen.tsx
  src/app/_small-talk/game-input/index.tsx
  src/app/_small-talk/game-random/game-random-screen.stories.tsx
  src/app/_small-talk/game-random/game-random-screen.tsx
  src/app/_small-talk/game-random/index.tsx
  src/app/_small-talk/game-result/game-random-screen.stories.tsx
  src/app/_small-talk/game-result/game-random-screen.tsx
  src/app/_small-talk/game-result/index.tsx
  src/app/stackflow.tsx
  src/assets/lotties/confetti.json
  src/assets/svgs/small-talk/reset-hint.svg
  src/assets/svgs/small-talk/reset.svg
  src/components/button/index.tsx
Labels: 🎨 design, ⚡feat, 📖 storybook

#38 docs: README UPDATE
  README.md
Labels: 📝docs

#40 feat: 컴포넌트 이미지 저장 기능을 구현합니다.
  package-lock.json
  package.json
  src/app/_mbti/_result/hooks/useLongPress.ts
  src/app/_mbti/_result/hooks/util.ts
  src/app/_mbti/_result/libs.ts
  src/app/_mbti/_result/mbti-all-result.tsx
  src/app/_mbti/_result/my-result.tsx
  src/app/_mbti/_result/team-result.tsx
  src/app/globals.css
  src/assets/images/mbti-result/planning.png
Labels: ⚡feat

#39 refactor: 작성한 코드 리팩토링
  .gitignore
  src/app/_game-loading/components/loading-bar/loading-bar.stories.tsx
  src/app/_game-loading/game-loading-screen.tsx
  src/app/_game-loading/game-loading.stories.tsx
  src/app/_main/components/main-button/index.tsx
  src/app/_main/components/main-button/main-button.stories.tsx
  src/app/_main/components/main-content/index.tsx
  src/app/_main/components/main-footer/index.tsx
  src/app/_main/main-screen.stories.tsx
  src/app/_main/main-screen.tsx
  src/app/_main/main.tsx
  src/app/_small-talk/components/game-banner/game-banner.stories.tsx
  src/app/_small-talk/components/game-banner/game-banner.tsx
  src/app/_small-talk/components/game-body/game-body.stories.tsx
  src/app/_small-talk/components/game-body/game-body.tsx
  src/app/_small-talk/game-input/game-input-screen.stories.tsx
  src/app/_small-talk/game-input/game-input-screen.tsx
  src/app/_small-talk/game-input/index.tsx
  src/app/_small-talk/game-random/game-random-screen.stories.tsx
  src/app/_small-talk/game-random/game-random-screen.tsx
  src/app/_small-talk/game-random/index.tsx
  src/app/_small-talk/game-result/game-random-screen.stories.tsx
  src/app/_small-talk/game-result/game-result-screen.stories.tsx
  src/app/_small-talk/game-result/game-result-screen.tsx
  src/app/_small-talk/game-result/index.tsx
  src/app/_waiting/components/waiting-bottom/index.tsx
  src/app/_waiting/components/waiting-top/index.tsx
  src/app/_waiting/waiting-screen.stories.tsx
  src/app/_waiting/waiting-screen.tsx
  src/app/_waiting/waiting.tsx
  src/app/apis/temp/route.ts
  src/constants/main.ts
  src/seeds/small-talk-mock.ts
  src/seeds/temp-mock.ts
  src/seeds/user-mock.ts
  src/store/admin-store.ts
  src/store/temp-store.ts
Labels: 🎨 design, 🔨 refactor, 📖 storybook

#48 feat: #47 유저 프로필 API를 연결합니다.
  src/app/_main/components/main-header/index.tsx
  src/app/_main/main-screen.stories.tsx
  src/app/_main/main-screen.tsx
  src/app/_main/main.tsx
  src/app/_profile/api/post-profile.ts
  src/app/_profile/profile-screen.tsx
  src/app/_profile/profile.tsx
  src/app/_small-talk/components/game-banner/game-banner.stories.tsx
  src/app/_small-talk/components/game-banner/game-banner.tsx
  src/app/_small-talk/components/game-body/game-body.tsx
  src/app/_small-talk/game-input/game-input-screen.stories.tsx
  src/app/_small-talk/game-input/game-input-screen.tsx
  src/app/_small-talk/game-input/index.tsx
  src/app/_small-talk/game-result/game-result-screen.tsx
  src/app/_waiting/components/waiting-top/index.tsx
  src/app/_waiting/types/game.ts
  src/app/_waiting/waiting.tsx
  src/constants/apis.ts
  src/seeds/user-mock.ts
  src/store/my-info-store.ts
  src/types/user.ts
Labels: 🔨 refactor, ⚡feat, 🖥️API

#49 feat: #44 waiting socket 연결
  env.d.ts
  src/app/_main/main-screen.tsx
  src/app/_select-games/select-games.tsx
  src/app/_waiting/components/waiting-bottom/index.tsx
  src/app/_waiting/components/waiting-bottom/one-user.tsx
  src/app/_waiting/components/waiting-bottom/user-list.tsx
  src/app/_waiting/components/waiting-top/index.tsx
  src/app/_waiting/waiting-screen.stories.tsx
  src/app/_waiting/waiting-screen.tsx
  src/app/_waiting/waiting.tsx
  src/app/page.tsx
  src/constants/apis.ts
  src/seeds/user-mock.ts
  src/store/admin-store.ts
  src/store/socket-store.ts
  src/types/waiting.ts
Labels: ⚡feat, 🚧test, 🖥️API

#51 feat: #50 GameSelect Screen API 연결
  src/app/_game-loading/game-loding.tsx
  src/app/_main/main-screen.tsx
  src/app/_select-games/select-games-screen.tsx
  src/app/_select-games/select-games.tsx
  src/app/_waiting/waiting-screen.tsx
  src/app/_waiting/waiting.tsx
  src/constants/apis.ts
Labels: ⚡feat, 🖥️API

#52 fix: admin이 아닐경우 이동이 안되는 버그를 제거하였습니다.
  src/app/_game-loading/game-loding.tsx
  src/app/_main/main-screen.tsx
  src/app/_select-games/select-games-screen.tsx
  src/app/_select-games/select-games.tsx
  src/app/_small-talk/game-input/game-input-screen.tsx
  src/app/_small-talk/game-input/index.tsx
  src/app/_waiting/waiting.tsx
  src/app/stackflow.tsx
  src/types/small-talk.ts
Labels: 🐞bug, ✅fix

#55 feat: #45 SmallTalk Screen API 연결
  src/app/_game-loading/game-loding.tsx
  src/app/_small-talk/game-input/game-input-screen.stories.tsx
  src/app/_small-talk/game-input/game-input-screen.tsx
  src/app/_small-talk/game-input/index.tsx
  src/app/_small-talk/game-random/game-random-screen.stories.tsx
  src/app/_small-talk/game-random/index.tsx
  src/app/_small-talk/game-result-list/game-random-screen.stories.tsx
  src/app/_small-talk/game-result-list/game-result-list-screen.tsx
  src/app/_small-talk/game-result-list/index.tsx
  src/app/_small-talk/game-result/game-result-screen.stories.tsx
  src/app/_small-talk/game-result/game-result-screen.tsx
  src/app/_small-talk/game-result/index.tsx
  src/app/_waiting/waiting.tsx
  src/app/stackflow.tsx
  src/constants/apis.ts
  src/seeds/small-talk-mock.ts
  src/types/small-talk.ts
Labels: ⚡feat, 🖥️API

#62 Update README.md
  README.md
Labels: 🔨 refactor, 📝docs

#59 feat: #45 small-talk 기능 완성
  src/app/_small-talk/game-input/index.tsx
  src/app/_small-talk/game-result-list/game-result-list-screen.tsx
  src/app/_small-talk/game-result-list/index.tsx
  src/app/_small-talk/game-result/game-result-screen.stories.tsx
  src/app/_small-talk/game-result/game-result-screen.tsx
  src/app/_small-talk/game-result/index.tsx
  src/constants/apis.ts
  src/store/blank-guide-store.ts
  src/types/small-talk.ts
Labels: ⚡feat, 🐞bug, 🖥️API
